# Generated by Django 5.0.6 on 2024-05-28 16:04

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showPrice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='pubDate',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
