# Generated by Django 5.0.6 on 2024-05-28 16:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showPrice', '0002_currency_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='pubDate',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
