# Generated by Django 5.0.6 on 2024-07-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPrice', '0003_alter_currency_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='showPrice.category'),
        ),
    ]
