# Generated by Django 5.0.6 on 2024-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showPrice', '0005_alter_currency_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
